scrape_configs:
  - job_name: 'ObsAppMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'Application'
